
FROM python:3.12-slim



RUN pip install --no-cache-dir --upgrade pip && \

    pip install --no-cache-dir setuptools==69.5.1 && \

    pip install --no-cache-dir mlflow==2.12.2 psycopg2-binary boto3



EXPOSE 5000



CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "postgresql+psycopg2://finsight:4115@postgres:5432/finsight", "--default-artifact-root", "/mlflow/artifacts", "--serve-artifacts"] 

